server:
  port: 8070
  
msg: Hello

spring:
  cloud:
    consul:
      discovery:
        tags: user.name=${security.user.name}, user.password=${security.user.password}

security:
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: svcb-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server